apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "product-service.selectorLabels" . | nindent 6 }}
